# Default values for csvserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: infracloudio/csvserver
  pullPolicy: IfNotPresent
  tag: latest

csvserver:
  containerPort: 9300
  mountpath: /csvserver/inputdata
  subpath: inputdata
  replica_count: 1
  env:
    CSVSERVER_BORDER: "Orange"
  servicePort: 9300
  
prometheus:
  containerPort: 9090
  scrape_interval: 5m
  image: prom/prometheus
  
service:
  type: ClusterIP
  port: 80

nodeport:
  port: 9090
  targetPort: 9090
  nodePort: 30000

