apiVersion: v1
kind: Service
metadata:  
  name: {{ .Release.Name }}-csvserver
spec:
  ports:
  - port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
  {{- include "csvserver.selectorLabels" .| nindent 4 -}} 


