apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  type: NodePort
  selector:
    {{- include "prometheus.labels" .| nindent 4 }}
  ports:
   - port: {{ .Values.nodeport.port }}
     targetPort: {{ .Values.nodeport.targetPort }}
     nodePort: {{  .Values.nodeport.nodePort }}
